version: '3.7'

services:
  fin_api:
    image: postgres
    container_name: fin_api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local